
--1. Member Table

CREATE TABLE Member (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    join_date DATE
);

--2. Librarian Table

CREATE TABLE Librarian (
    librarian_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    hire_date DATE
);

-- 3. Book Table

CREATE TABLE Book (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    author VARCHAR2(100),
    isbn VARCHAR2(20) UNIQUE,
    category VARCHAR2(100),
    availability CHAR(1) DEFAULT 'Y' 
        CONSTRAINT chk_availability CHECK (availability IN ('Y', 'N')) -- Y = Available, N = Issued
);

--4. Issue_Record Table

CREATE TABLE Issue_Record (
    issue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    librarian_id NUMBER NOT NULL,
    issue_date DATE NOT NULL,
    return_date DATE,
    CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES Member(member_id),
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES Book(book_id),
    CONSTRAINT fk_librarian FOREIGN KEY (librarian_id) REFERENCES Librarian(librarian_id)
);